# Generated by Django 4.2.5 on 2023-09-25 02:41

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_customuser2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
