# Generated by Django 4.2.5 on 2023-09-25 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_posts_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='snippet',
            field=models.CharField(default='Click Link To View', max_length=255),
        ),
    ]
