# Generated by Django 4.2.5 on 2023-09-27 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_replies_delete_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser2',
            name='user_type',
        ),
        migrations.AddField(
            model_name='posts',
            name='files',
            field=models.ImageField(blank=True, null=True, upload_to='post_files/'),
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
