# Generated by Django 4.2.5 on 2023-09-27 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_remove_customuser2_user_type_posts_files_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='files',
        ),
        migrations.CreateModel(
            name='PostFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='post_files/')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.posts')),
            ],
        ),
        migrations.AddField(
            model_name='posts',
            name='files',
            field=models.ManyToManyField(blank=True, related_name='posts', to='account.postfile'),
        ),
    ]
