# Generated by Django 4.2.5 on 2023-10-01 22:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0013_account_remove_posts_files_delete_postfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='replies',
            name='name',
        ),
        migrations.AddField(
            model_name='replies',
            name='author',
            field=models.CharField(max_length=255, null=True),
            preserve_default=False,
        ),
    ]
