# Generated by Django 4.2.5 on 2023-10-01 22:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_remove_replies_name_replies_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='replies',
            name='author',
        ),
        migrations.AddField(
            model_name='replies',
            name='name',
            field=models.CharField(max_length=255, null=True),
            preserve_default=False,
        ),
    ]
