# Generated by Django 4.2.5 on 2023-10-01 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_remove_replies_author_replies_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
