# Generated by Django 4.2.5 on 2023-10-03 16:37

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_posts_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replies',
            name='name',
            field=models.CharField(max_length=255, default="Unknown"),
            preserve_default=False,
        ),
    ]
