# Generated by Django 4.2.5 on 2023-10-03 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_alter_replies_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replies',
            name='name',
            field=models.CharField(default='Unknown', max_length=255),
        ),
    ]
