# Generated by Django 4.2.5 on 2023-11-04 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0007_alter_quiz_course'),
        ('account', '0020_alter_posts_post_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='teachers.course'),
        ),
    ]
