# Generated by Django 4.2.5 on 2023-11-21 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_alter_posts_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser2',
        ),
    ]
