# Generated by Django 4.2.5 on 2023-11-05 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0009_grade_attempts_grade_highest_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='highest_grade',
        ),
        migrations.AddField(
            model_name='quiz',
            name='highest_grade',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
