# Generated by Django 4.2.5 on 2023-11-05 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0010_remove_grade_highest_grade_quiz_highest_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='highest_grade',
        ),
    ]
