# Generated by Django 4.2.5 on 2023-11-05 23:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0011_remove_quiz_highest_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
