# Generated by Django 4.2.5 on 2023-11-21 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0012_grade_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='weights',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='quiz',
            name='weight',
            field=models.FloatField(default=0.0),
        ),
    ]
