# Generated by Django 4.2.5 on 2023-11-24 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0013_question_weights_quiz_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='weights',
        ),
        migrations.AddField(
            model_name='question',
            name='points',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='weight',
            field=models.IntegerField(default=100),
        ),
    ]
