# Generated by Django 4.2.5 on 2023-11-24 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0015_grade_percentile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='percentile',
        ),
    ]
