# Generated by Django 4.2.5 on 2023-11-24 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0016_remove_grade_percentile'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='user_score',
            field=models.IntegerField(default=0),
        ),
    ]
