# Generated by Django 4.2.5 on 2023-11-24 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0017_grade_user_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='max_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='grade',
            name='user_score',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
