# Generated by Django 4.2.5 on 2023-11-24 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0018_grade_max_score_alter_grade_user_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='max_score',
        ),
        migrations.AddField(
            model_name='course',
            name='points',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
