# Generated by Django 4.2.5 on 2023-11-24 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0020_grade_max_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='max_score',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
