# Generated by Django 4.2.5 on 2023-11-24 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0021_alter_grade_max_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='grade',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
